version: 2.1

workflows:
  workflow:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test:
          matrix:
            parameters:
              node_version: [lts]
          filters:
            tags:
              only: /.*/


commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: npm ci

jobs:
  lint:
    working_directory: /mnt/ramdisk
    docker:
      - image: cimg/node:lts
    steps:
      - setup
      - run:
          command: npm run lint
          when: always

  test:
    parameters:
      node_version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node_version >>
    working_directory: /mnt/ramdisk
    steps:
      - setup
      - run: NODE_OPTIONS=--openssl-legacy-provider npm test
